### ISSUE TITLE
Error using PyUSB on Linux in VMWare

### ISSUE THREAD

**Issue by j4m410** [pyusb/pyusb#216]
Hi there,

im using a GreatFet Board with the corresponding Python library ([https://github.com/greatscottgadgets/greatfet](https://github.com/greatscottgadgets/greatfet)).
If im trying to run one of those functions, i end up having an error from PyUSB:

Traceback (most recent call last):
  File "/usr/local/bin/greatfet_info", line 11, in <module>
    load_entry_point('GreatFET==0.0', 'console_scripts', 'greatfet_info')()

File "/usr/local/lib/python3.7/dist-packages/GreatFET-0.0-py3.7.egg/greatfet/commands/greatfet_info.py", line 17, in main
    devices = GreatFET(find_all=True)

File "/usr/local/lib/python3.7/dist-packages/GreatFET-0.0-py3.7.egg/greatfet/greatfet.py", line 29, in GreatFET
    return GreatFETBoard.autodetect_all(**board_identifiers)

File "/usr/local/lib/python3.7/dist-packages/GreatFET-0.0-py3.7.egg/greatfet/board.py", line 100, in autodetect_all
    subclass_devices = subclass.all_accepted_devices(**device_identifiers)

File "/usr/local/lib/python3.7/dist-packages/GreatFET-0.0-py3.7.egg/greatfet/board.py", line 141, in all_accepted_devices
    if cls.accepts_connected_device(**identifiers):

File "/usr/local/lib/python3.7/dist-packages/GreatFET-0.0-py3.7.egg/greatfet/boards/flash_stub.py", line 47, in accepts_connected_device
    potential_device = cls(**device_identifiers)

File "/usr/local/lib/python3.7/dist-packages/GreatFET-0.0-py3.7.egg/greatfet/boards/flash_stub.py", line 30, in __init__
    super(GreatFETOne, self).__init__(**device_identifiers)

File "/usr/local/lib/python3.7/dist-packages/GreatFET-0.0-py3.7.egg/greatfet/board.py", line 239, in __init__
    self._initialize_usb()

File "/usr/local/lib/python3.7/dist-packages/GreatFET-0.0-py3.7.egg/greatfet/board.py", line 251, in _initialize_usb
    self.device.set_configuration()

File "/usr/local/lib/python3.7/dist-packages/pyusb-1.0.2-py3.7.egg/usb/core.py", line 869, in set_configuration

File "/usr/local/lib/python3.7/dist-packages/pyusb-1.0.2-py3.7.egg/usb/core.py", line 102, in wrapper

File "/usr/local/lib/python3.7/dist-packages/pyusb-1.0.2-py3.7.egg/usb/core.py", line 148, in managed_set_configuration

File "/usr/local/lib/python3.7/dist-packages/pyusb-1.0.2-py3.7.egg/usb/backend/libusb1.py", line 794, in set_configuration

File "/usr/local/lib/python3.7/dist-packages/pyusb-1.0.2-py3.7.egg/usb/backend/libusb1.py", line 595, in _check
usb.core.USBError: [Errno None] Other error

My system is a Kali Linux running as virtual machine (VMWare) with libusb1 installed.
Already tried it on other VMs, but the same error occurs. Running the script directly on the host works perfectly.

**Comment by mcuee** [comment]
Then it is a VMware issue and please get help from them.
