### ISSUE TITLE
Error Access String Interfaces.

### ISSUE THREAD

**Issue by search5** [pyusb/pyusb#225]
If you run the python script below and run it again, you will get the error message below. I do not know what to do if I run the lsusb command. I hope you can help solve this problem.

thank you.

test.py script:
```
import usb.core
import usb.util

""" Seiko Epson Corp. Receipt Printer M129 Definitions (EPSON TM-T88IV) """

p = usb.core.find(idVendor=0x0456, idProduct=0x0808)
p.set_configuration()
cfg = p.get_active_configuration()
intf = cfg[(0, 0)]
ep = usb.util.find_descriptor(
    intf,
    # match the first OUT endpoint
    custom_match = \
    lambda e: \
        usb.util.endpoint_direction(e.bEndpointAddress) == \
        usb.util.ENDPOINT_OUT)
ep.write('test')
```

error stack
```
2018-12-14 14:33:47,400 DEBUG:usb.backend.libusb1:_LibUSB.__init__(<CDLL 'libusb-1.0.so.0', handle 55ba34d81910 at 0x7f6232e62940>)
2018-12-14 14:33:47,402 INFO:usb.core:find(): using backend "usb.backend.libusb1"
2018-12-14 14:33:47,402 DEBUG:usb.backend.libusb1:_LibUSB.enumerate_devices()
2018-12-14 14:33:47,402 DEBUG:usb.backend.libusb1:_LibUSB.get_device_descriptor(<usb.backend.libusb1._Device object at 0x7f623235ea90>)
2018-12-14 14:33:47,403 DEBUG:usb.backend.libusb1:_LibUSB.get_device_descriptor(<usb.backend.libusb1._Device object at 0x7f622e9aef60>)
2018-12-14 14:33:47,403 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x7f622e9aef60>, 0)
2018-12-14 14:33:47,403 DEBUG:usb.backend.libusb1:_LibUSB.open_device(<usb.backend.libusb1._Device object at 0x7f622e9aef60>)
2018-12-14 14:33:47,403 DEBUG:usb.backend.libusb1:_LibUSB.set_configuration(<usb.backend.libusb1._DeviceHandle object at 0x7f6232e79978>, 1)
Traceback (most recent call last):
  File "test2.py", line 10, in <module>
    p.set_configuration()
  File "/home/jiho/.virtualenvs/insignal/lib/python3.6/site-packages/usb/core.py", line 870, in set_configuration
    self._ctx.managed_set_configuration(self, configuration)
  File "/home/jiho/.virtualenvs/insignal/lib/python3.6/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/home/jiho/.virtualenvs/insignal/lib/python3.6/site-packages/usb/core.py", line 148, in managed_set_configuration
    self.backend.set_configuration(self.handle, cfg.bConfigurationValue)
  File "/home/jiho/.virtualenvs/insignal/lib/python3.6/site-packages/usb/_debug.py", line 60, in do_trace
    return f(*args, **named_args)
  File "/home/jiho/.virtualenvs/insignal/lib/python3.6/site-packages/usb/backend/libusb1.py", line 794, in set_configuration
    _check(self.lib.libusb_set_configuration(dev_handle.handle, config_value))
  File "/home/jiho/.virtualenvs/insignal/lib/python3.6/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 16] Resource busy
2018-12-14 14:33:47,419 DEBUG:usb.backend.libusb1:_LibUSB.close_device(<usb.backend.libusb1._DeviceHandle object at 0x7f6232e79978>)
2018-12-14 14:33:47,419 DEBUG:usb.backend.libusb1:_LibUSB._finalize_object()
```

Note that this usb device is a POS printer. We will use the python-escpos package to control this printer.

lsusb -v result
```
$ lsusb -vvv -d 0456:0808

Bus 002 Device 006: ID 0456:0808 Analog Devices, Inc. 
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x0456 Analog Devices, Inc.
  idProduct          0x0808 
  bcdDevice            2.00
  iManufacturer           1 STMicroelectronics
  iProduct                2 POS58 Printer USB       
  iSerial                 3 Printer
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           32
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          5 (error)
    bmAttributes         0xc0
      Self Powered
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass         7 Printer
      bInterfaceSubClass      1 Printer
      bInterfaceProtocol      2 Bidirectional
      iInterface              4 (error)
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x03  EP 3 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
Device Status:     0x0001
  Self Powered```

**Comment by mcuee** [comment]
If there is already a kernel driver attached to this device, you have to detach the kernel driver. Depending on your os, you will need to carry out different procedures to do what you want.
