### ISSUE TITLE
[Errno 2] Entity not found - code from tutorial, with converting generator to list

### ISSUE THREAD

**Issue by C0oo1D** [pyusb/pyusb#234]
`printers = usb.core.find(find_all=1, custom_match=FindClass(7))`
changed to 
`printers = list(usb.core.find(find_all=1, custom_match=FindClass(7)))`

> Traceback (most recent call last):
  File "..test.py", line 25, in <module>
    printers = list(usb.core.find(find_all=1, custom_match=FindClass(7)))
  File "..\usb\core.py", line 1249, in device_iter
    if _interop._all(tests) and (custom_match is None or custom_match(d)):
  File "..test.py", line 14, in __call__
    for cfg in device:
  File "..\usb\core.py", line 1094, in __iter__
    yield Configuration(self, i)
  File "..\usb\core.py", line 586, in __init__
    configuration
  File "..\usb\backend\libusb1.py", line 757, in get_configuration_descriptor
    config, byref(cfg)))
  File "..\usb\backend\libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 2] Entity not found

**Comment by mcuee** [comment]
Please use pyusb mailing list for technical support.
