### ISSUE TITLE
usb.core.USBError: [Errno None] b'libusb0-dll:err [control_msg] sending control message failed

### ISSUE THREAD

**Issue by weizdu** [pyusb/pyusb#28]
I used following lamp and installed libusb-win32 (v1.2.6.0) using zadig.
http://dx.com/p/usb-universal-e-mail-webmail-im-notifier-gmail-outlook-outlook-express-pop3-27062

And I used following python script to sending msg to usb.
https://code.google.com/p/usbmailnotifier/

But, I got these faults as below:
D:\Python33\pyusb-master>python setcolor.py 5
<usb.legacy.Bus object at 0x01BD66D0>
[<usb.legacy.Device object at 0x01BDED30>]
Traceback (most recent call last):
  File "setcolor.py", line 62, in <module>
    main(sys.argv)
  File "setcolor.py", line 59, in main
    m.setColor(int(argv[1]))
  File "setcolor.py", line 18, in setColor
    self.dev.handle.interruptWrite(0x02, self.makeData(color), 1000)
  File "D:\Python33\pyusb-master\usb\legacy.py", line 171, in interruptWrite
    return self.dev.write(endpoint, buffer, self.__claimed_interface, timeout)
  File "D:\Python33\pyusb-master\usb\core.py", line 623, in write
    intf = self._ctx.get_interface(self, interface)
  File "D:\Python33\pyusb-master\usb\core.py", line 150, in get_interface
    cfg = self.get_active_configuration(device)
  File "D:\Python33\pyusb-master\usb\core.py", line 165, in get_active_configura
tion
    bConfigurationValue=self.backend.get_configuration(self.handle)
  File "D:\Python33\pyusb-master\usb\backend\libusb0.py", line 464, in get_confi
guration
    100
  File "D:\Python33\pyusb-master\usb\backend\libusb0.py", line 544, in ctrl_tran
sfer
    timeout
  File "D:\Python33\pyusb-master\usb\backend\libusb0.py", line 392, in _check
    raise USBError(errmsg, ret)
usb.core.USBError: [Errno None] b'libusb0-dll:err [control_msg] sending control
message failed, win error: \xcf\xb5\xcd\xb3\xd5\xd2\xb2\xbb\xb5\xbd\xd6\xb8\xb6\
xa8\xb5\xc4\xce\xc4\xbc\xfe\xa1\xa3\r\n\n'

**Comment by lzh01993** [comment]
Hello ,I have meet a problem about pyusb in windows .I need to use a api about the device of  power monitor to shart sample.I got a error like this error ,I want to know if this problem have been solved.there are my error:
C:\Users\zihaliu\Downloads\monsoon-0.1.64\monsoon-0.1.64\Monsoon>python sample.p
y
Control Transfer Error
Traceback (most recent call last):
  File "sample.py", line 28, in <module>
    engine.startSampling(numSamples)
  File "C:\Python27\lib\site-packages\monsoon-0.1.64-py2.7.egg\Monsoon\sampleEng
ine.py", line 454, in startSampling
    self.monsoon.StartSampling(1250,0xFFFFFFFF)
  File "C:\Python27\lib\site-packages\monsoon-0.1.64-py2.7.egg\Monsoon\LVPM.py",
 line 160, in StartSampling
    self.fillStatusPacket()
  File "C:\Python27\lib\site-packages\monsoon-0.1.64-py2.7.egg\Monsoon\LVPM.py",
 line 133, in fillStatusPacket
    self.statusPacket.mainFineResistorOffset = float(Protocol.getValue(op.OpCode
s.setMainFineResistorOffset,1))
  File "C:\Python27\lib\site-packages\monsoon-0.1.64-py2.7.egg\Monsoon\pmapi.py"
, line 40, in getValue
    result = self.DEVICE.ctrl_transfer(op.Control_Codes.USB_IN_PACKET,op.Control
_Codes.USB_SET_VALUE,0,wIndex,4,5000)
  File "C:\Python27\lib\site-packages\usb\core.py", line 711, in ctrl_transfer
    self.__get_timeout(timeout)
  File "C:\Python27\lib\site-packages\usb\backend\libusb0.py", line 544, in ctrl
_transfer
    timeout
  File "C:\Python27\lib\site-packages\usb\backend\libusb0.py", line 392, in _che
ck
    raise USBError(errmsg, ret)
usb.core.USBError: [Errno None] libusb0-dll:err [control_msg] sending control me
ssage failed, win error: A device attached to the system is not functioning.
