### ISSUE TITLE
Pipe error when using control transfers on multiple devices

### ISSUE THREAD

**Issue by andrew-pomerance** [pyusb/pyusb#351]
Hi, I'm having an issue using PyUSB with multiple (identical) devices.  I have 3 devices hooked up to a Windows 10 box, and the code
```
print([dev.serial_number for dev in usb.core.find(idVendor=0x221A, find_all=True)])
```
works fine and prints out the serial numbers as expected.  However, when I try to send a control transfer to them, like so:
```
    for dev in usb.core.find(idVendor=0x221A, find_all=True):
        dev.set_configuration(1)
        dev.ctrl_transfer(64, 0x62, 0, 0, b'\xff\xff\xff\xff\xff')
```

I get the following exception on _second_ device:
```
  File "experiment.py", line 55, in <module>
    dev.ctrl_transfer(64, 0x62, 0, 0, b'\xff\xff\xff\xff\xff')
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python37\lib\site-packages\usb\core.py", line 1077, in ctrl_transfer
    self.__get_timeout(timeout))
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python37\lib\site-packages\usb\backend\libusb1.py", line 901, in ctrl_transfer
    timeout))
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python37\lib\site-packages\usb\backend\libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 32] Pipe error
```

That is, the `ctrl_transfer` works fine on the first one in the loop. Okay, so now I tried filtering by serial number like so:

```
    serial_numbers = ['1EC0AF42A4', '1EC0AF692E', '1EC0AF1A4A']

    def serial(serial_num):
        return lambda dev: dev.serial_number == serial_num

    for serial_num in serial_numbers:
        dev = usb.core.find(idVendor=0x221A, custom_match=serial(serial_num))
        print('found')
```
The first time through the loop, searching for 1EC0AF42A4, prints found, but again on the second time through the loop for 1EC0AF692E I get:
```
Traceback (most recent call last):
  File "experiment.py", line 55, in <module>
    dev = usb.core.find(idVendor=0x221A, custom_match=serial(serial_num))
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python37\lib\site-packages\usb\core.py", line 1303, in find
    return _interop._next(device_iter(**args))
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python37\lib\site-packages\usb\_interop.py", line 68, in _next
    return next(iter)
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python37\lib\site-packages\usb\core.py", line 1283, in device_iter
    if _interop._all(tests) and (custom_match is None or custom_match(d)):
  File "experiment.py", line 52, in <lambda>
    return lambda dev: dev.serial_number == serial_num
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python37\lib\site-packages\usb\core.py", line 852, in serial_number
    self._serial_number = util.get_string(self, self.iSerialNumber)
  File "C:\Users\Andrew\AppData\Local\Programs\Python\Python37\lib\site-packages\usb\util.py", line 313, in get_string
    raise ValueError("The device has no langid"
ValueError: The device has no langid (permission issue, no string descriptors supported or device error)
```

Is this a bug or am I doing something irresponsible?  I'm guessing something's being left open, but I tried calling reset in the loop but that had no effect as well.

Thanks,
Andrew

**Comment by andrew-pomerance** [comment]
For what it's worth, I found that it was actually a bug in the firmware on the second device.  Works like a charm with reflashing...
