### ISSUE TITLE
usb.core.USBError: [Errno 32] Pipe error after some time

### ISSUE THREAD

**Issue by danielhrisca** [pyusb/pyusb#414]
Hello,

I'm getting this error while reading. The communication works fine for about 3 minutes and then this is triggered. 

I'm using an array for the reads, the essential code looks roughly like this:

```python

data_buffer = array("B", bytes(RECV_SIZE))

while True:
    read_count = endpoint.read(data_buffer, 1) 
    if not read_count:
            sleep(0.01)
            continue
    # some data processing here
```

and the traceback looks like this

```
Traceback (most recent call last):
  File "D:\DSUsers\uidn3651\02__PythonWorkspace\project_2\project\xil\devices\zbox.py", line 364, in _data_listen
    read_count = endpoint.read(data_buffer, 1) 
  File "D:\TMP\project_venv_3.9\lib\site-packages\usb\core.py", line 423, in read
    return self.device.read(self, size_or_buffer, timeout)
  File "D:\TMP\project_venv_3.9\lib\site-packages\usb\core.py", line 1029, in read
    ret = fn(
  File "D:\TMP\project_venv_3.9\lib\site-packages\usb\backend\libusb1.py", line 846, in bulk_read
    return self.__read(self.lib.libusb_bulk_transfer,
  File "D:\TMP\project_venv_3.9\lib\site-packages\usb\backend\libusb1.py", line 954, in __read
    _check(retval)
  File "D:\TMP\project_venv_3.9\lib\site-packages\usb\backend\libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 32] Pipe error
```

What could I do to mitigate this problem?

Thank you!

**Comment by jonasmalacofilho** [comment]
Hi @danielhrisca,

Sorry for the delay, I almost lost the notification for this issue...

Please take a look at https://github.com/pyusb/pyusb/discussions/411#discussioncomment-2138235 for some general information about how to investigate a problem like this.  That comment deals with a different libusb API, so make sure to check the correct docs for the one being called here (`libusb_bulk_transfer`).

Also, issues like these usually arise from the device, and commonly require from you a better understanding of the protocol and requirements in use by the device.

---

P.S. Moving this to Discussions/Q/A.
