### ISSUE TITLE
usb.core.USBError: [Errno None] b'libusb0-dll:err [control_msg] sending control message failed, win error: \xc1\xac\xb5\xbd\xcf\xb5\xcd\xb3\xc9\xcf\xb5\xc4\xc9\xe8\xb1\xb8\xc3\xbb\xd3\xd0\xb7\xa2\xbb\xd3\xd7\xf7\xd3\xc3\xa1\xa3\r\n\n'

### ISSUE THREAD

**Issue by vgegok** [pyusb/pyusb#467]
`C:\Users\vgegok>python
Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import usb.core
>>> import usb.util
>>> dev = usb.core.find(idVendor=0x04b4, idProduct=0x00f1)
>>> dev.set_configuration()
>>> ret = dev.ctrl_transfer(0x40, 0xC1, 0, 1, None, 1000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\vgegok\AppData\Local\Programs\Python\Python311\Lib\site-packages\usb\core.py", line 1082, in ctrl_transfer
    ret = self._ctx.backend.ctrl_transfer(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vgegok\AppData\Local\Programs\Python\Python311\Lib\site-packages\usb\backend\libusb0.py", line 601, in ctrl_transfer
    return _check(_lib.usb_control_msg(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vgegok\AppData\Local\Programs\Python\Python311\Lib\site-packages\usb\backend\libusb0.py", line 447, in _check
    raise USBError(errmsg, ret)
usb.core.USBError: [Errno None] b'libusb0-dll:err [control_msg] sending control message failed, win error: \xc1\xac\xb5\xbd\xcf\xb5\xcd\xb3\xc9\xcf\xb5\xc4\xc9\xe8\xb1\xb8\xc3\xbb\xd3\xd0\xb7\xa2\xbb\xd3\xd7\xf7\xd3\xc3\xa1\xa3\r\n\n'
>>>`

**Comment by jonasmalacofilho** [comment]
Sorry, but (from the little you shared) this doesn't seem to relate to PyUSB: it looks like a backend (libusb0, in this case) or OS error, or perhaps you've got the protocol wrong. Closing.
