### ISSUE TITLE
usb.core.USBError: [Errno 19] No such device (mac os M1)

### ISSUE THREAD

**Issue by chavilaw** [pyusb/pyusb#476]
Getting usb and backend errors, for example: (i am running it with Mac os M1)
but like dev is present, i do get this for output

**--->>>> Found ACR122U**

`Traceback (most recent call last):
  File "/Users/username/nfc_reader/tag_scan.py", line 14, in <module>
    dev.set_configuration()
  File "/opt/homebrew/lib/python3.11/site-packages/usb/core.py", line 915, in set_configuration
    self._ctx.managed_set_configuration(self, configuration)
  File "/opt/homebrew/lib/python3.11/site-packages/usb/core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/usb/core.py", line 159, in managed_set_configuration
    self.backend.set_configuration(self.handle, cfg.bConfigurationValue)
  File "/opt/homebrew/lib/python3.11/site-packages/usb/backend/libusb1.py", line 812, in set_configuration
    _check(self.lib.libusb_set_configuration(dev_handle.handle, config_value))
  File "/opt/homebrew/lib/python3.11/site-packages/usb/backend/libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 19] No such device (it may have been disconnected)`

the program i ran is:

`import usb.core
import usb.util

# Find the USB device
dev = usb.core.find(idVendor=0x072f, idProduct=0x2200)

# If the device is not found, raise an exception
if dev is None:
    raise ValueError('Device not found')
else:
    print('Found ACR122U')

# Set the active configuration
dev.set_configuration()

# Read the data from the device
data = dev.read(0x81, 0x08)

# Convert the data to a string and print it
text = ''.join([chr(x) for x in data])
print('NFC tag data:', text)
`

also I have already installed libusb. thanks!

**Comment by mcuee** [comment]
What is this device? If this device has already a kernel driver or application which has exclusive access to the device, then you can not use libusb/pyusb with the device.
